{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
#  name: {{ .Release.Name }}
  name: {{ include "dropw-app.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
#    name: {{ .Release.Name }}
    name: {{ include "dropw-app.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.cpu }}
  {{- end }}
#  {{- if .Values.hpa.memory }}
#  - type: Resource
#    resource:
#      name: memory
#      targetAverageValue: {{ .Values.hpa.memory }}
#  {{- end }}
#  {{- if .Values.hpa.requests }}
#  - type: Pod
#      pods:
#        metricName: http_requests
#        targetAverageValue: {{ .Values.hpa.requests }}
#  {{- end }}
{{- end }}