apiVersion: v1
kind: Service
metadata:
  name: alb-metrics-svc
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
  - name: alb-metrics-port
    protocol: TCP
    port: 9913
  selector:
    app: ibmcloud-alb-metrics-exporter