prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name 
  ingress:
    enabled: true
    annotations:
      ingress.bluemix.net/redirect-to-https: "True"
    hosts:
      - prometheus.devcluster.eu-de.containers.appdomain.cloud
    tls:
    - secretName: devcluster
      hosts:
        - prometheus.devcluster.eu-de.containers.appdomain.cloud

alertmanager:
  ingress:
    enabled: true
    annotations:
      ingress.bluemix.net/redirect-to-https: "True"
    hosts:
      - alertmanager.devcluster.eu-de.containers.appdomain.cloud
    tls: 
    - secretName: devcluster
      hosts:
        - alertmanager.devcluster.eu-de.containers.appdomain.cloud

grafana:
  ingress:
    enabled: true
    annotations:
      ingress.bluemix.net/redirect-to-https: "True"
    hosts:
      - grafana.devcluster.eu-de.containers.appdomain.cloud
    tls:
    - secretName: devcluster
      hosts:
        - grafana.devcluster.eu-de.containers.appdomain.cloud
