# Default values for ibmcloud-alb-metrics-exporter-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: icr.io/ibm/ibmcloud-alb-metrics-exporter
  tag: 10

name: ibmcloud-alb-metrics-exporter

# namespace for metrics exporters and service account, e.g. ibm-system
metricsNameSpace: "kube-system"

# use 'ibmcloud ks albs --cluster mycluster' to find out albID of your cluster, e.g. public-cr8d29a4bba797466aa99701d170d6b7db-alb1
albId: "public-cr1bab796d7cdb46738cd24d1731663d68-alb1"

# namespace for alb pods, if emtpy, default to 'kube-system'
albNameSpace: "kube-system"

internalPort: 9899
topologyKey: kubernetes.io/hostname
prometheusAgentEnable: true
