apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-vol
  labels:
     app: jenkins-ci
     env: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-file-bronze